package crucigrama.metodos;

public class Enunciados {
	public static void  enunciados (String [][] lineas) { 
		
	String[][] enunciados = {
	        // NIVEL FÁCIL - Fase 1 (6-7 letras)
			// ============ NIVEL FÁCIL FASE 1 ============
	        {"CASA", "Refugio de cuatro paredes y un techo"},
	        {"MESA", "Plano que carga sin protestar"},
	        {"PERRO", "Guardián con cola y lealtad"},
	        {"GATO", "Cazador silencioso de interior"},
	        {"LUNA", "Farol nocturno que mengua y crece"},
	        {"FLOR", "Color que nace en el tallo"},
	        {"MAR", "Desierto líquido con olas"},
	        {"RIO", "Sendero de agua que corre"},
	        {"NUBE", "Almohada flotante que llora"},
	        {"HOJA", "Piel verde del árbol"},
	        {"ARBOL", "Gigante de raíces y ramas"},
	        {"PAN", "Sol dorado comestible"},
	        {"LEON", "Rey sin corona de la sabana"},
	        {"OSO", "Peluche peligroso del bosque"},
	        {"RATA", "Sombra rápida en la oscuridad"},
	        {"PEZ", "Plata que nada en cristal"},
	        {"AVE", "Canto con plumas y vuelo"},
	        {"RED", "Telaraña para atrapar"},
	        {"SILLA", "Trono de descanso doméstico"},
	        {"PUERTA", "Boca de la casa que se abre"},
	        {"VENTANA", "Ojo de la pared al mundo"},
	        {"COCHE", "Corcel metálico con ruedas"},
	        {"BARCO", "Casa que flota sobre agua"},
	        {"AVION", "Pájaro de metal que cruza cielos"},
	        {"BICI", "Caballo de hierro con pedales"},
	        {"MOTO", "Furia con dos ruedas y motor"},
	        {"RUEDA", "Círculo que rueda sin caminar"},
	        {"CALLE", "Río de asfalto por donde caminan"},
	        {"PLAZA", "Sala sin techo de la ciudad"},
	        {"PARQUE", "Pulmón verde entre cemento"},
	        {"LIBRO", "Páginas encuadernadas que hablan"},
	        {"LAPIZ", "Varita mágica que dibuja ideas"},
	        {"PAPEL", "Piel blanca para palabras"},
	        {"FOTO", "Recuerdo capturado en rectángulo"},
	        {"VIDEO", "Memoria en movimiento digital"},
	        {"MUSICA", "Matemática audible del alma"},
	        {"BAILE", "Poesía con los pies"},
	        {"JUEGO", "Seriedad disfrazada de diversión"},
	        {"GOL", "Red que atrapa aplausos"},
	        {"PELOTA", "Esfera que salta por órdenes"},
	        {"JARDIN", "Cuadro vivo que crece"},
	        {"FUENTE", "Agua que baila vertical"},
	        {"CUADRO", "Ventana a otro mundo plano"},
	        {"CANTO", "Voz que se convierte en ave"},
	        {"DEPORTE", "Guerra civilizada con reglas"},
	        {"PASE", "Pase de la pelota"},
	        {"TIRO", "Flecha sin arco"},
	        {"RAQUETA", "Red en marco que golpea"},
	        {"CAMPO", "Mar verde sin agua"},
	        {"AMIGO", "Espejo que nos elige"},
	        {"FAMILIA", "Tribu sanguínea obligatoria"},
	        {"HERMANO", "Extraño con tu misma sangre"},
	        {"PADRE", "Árbol genealógico viviente"},
	        {"MADRE", "Raíz primera del ser"},
	        {"HIJO", "Espejo futuro de uno mismo"},
	        {"TIO", "Padre secundario por sangre"},
	        {"TIA", "Madre de refuerzo familiar"},
	        {"ABUELO", "Historia viviente con arrugas"},
	        {"NIETO", "Futuro que abraza al pasado"},
	        {"ESCUELA", "Fábrica de ciudadanos"},
	        {"CLASE", "Cápsula de conocimiento diario"},
	        {"ALUMNO", "Vaso vacío que espera llenarse"},
	        {"PROFE", "Guía pagado del saber"},
	        {"AULA", "Cuadrilátero del aprendizaje"},
	        {"PATIO", "Libertad vigilada entre clases"},
	        {"RECREO", "Respiro entre conocimiento"},
	        {"EXAMEN", "Juicio escrito del saber"},
	        {"NOTA", "Número que mide esfuerzo"},
	        {"CURSO", "Camino académico anual"},
	        {"COMIDA", "Combustible humano con sabor"},
	        {"AGUA", "Transparencia que da vida"},
	        {"LECHE", "Blanco líquido nutritivo"},
	        {"CARNE", "Musculo ajeno que comemos"},
	        {"FRUTA", "Dulzura natural con piel"},
	        {"VERDURA", "Color verde comestible"},
	        {"ARROZ", "Blanco que acompaña todo"},
	        {"PASTA", "Harina moldeada en formas"},
	        {"TIEMPO", "Jefe invisible que pasa"},
	        {"HORA", "Trozo medido del tiempo"},
	        {"DIA", "Luz regalada por rotación"},
	        {"NOCHE", "Manto oscuro con estrellas"},
	        {"SEMANA", "Ciclo de siete días"},
	        {"MES", "Luna medida en días"},
	        {"ANO", "Vuelta completa al sol"},
	        {"FECHA", "Coordenada en el calendario"},
	        {"RELOJ", "Corazón mecánico del tiempo"},
	        {"CALENDARIO", "Mapa de los días por venir"},
	        {"INVIERNO", "Frío que hiberna la vida"},
	        {"VERANO", "Sol que madura la piel"},
	        {"OTOÑO", "Melancolía multicolor"},
	        {"PRIMAVERA", "Renacimiento anual de colores"},
	        {"ENERO", "Puerta fría del año"},
	        {"FEBRERO", "Mes corto que a veces salta"},
	        {"MARZO", "Entrada incierta de primavera"},
	        {"ABRIL", "Lluvia con olor a flores"},
	        {"MAYO", "Flores antes del calor"},
	        {"JUNIO", "Principio del verano"},
	        {"JULIO", "Fuego estival en nombre"},
	        {"AGOSTO", "Vacío urbano por vacaciones"},
	        {"SEPTIEMBRE", "Vuelta al orden después del sol"},
	        
	        // ============ NIVEL FÁCIL FASE 2 ============
	        {"TELEVISION", "Caja luminosa que hipnotiza"},
	        {"RADIO", "Voz invisible por ondas"},
	        {"TELEFONO", "Puente de voz a distancia"},
	        {"CELULAR", "Mundo en la palma de la mano"},
	        {"TABLETA", "Ventana portátil al digital"},
	        {"PORTATIL", "Oficina plegable personal"},
	        {"COCINA", "Laboratorio de transformación alimenticia"},
	        {"DORMITORIO", "Santuario del sueño reparador"},
	        {"BANIO", "Templo de la higiene diaria"},
	        {"SALON", "Corazón social del hogar"},
	        {"GARAJE", "Establo para corceles mecánicos"},
	        {"TERRAZA", "Balcón al cielo urbano"},
	        {"BALCON", "Pestaña de la casa al exterior"},
	        {"ASCENSOR", "Caja mágica que sube y baja"},
	        {"ESCALERA", "Montaña artificial de peldaños"},
	        {"PASILLO", "Corredor entre espacios"},
	        {"HOSPITAL", "Santuario de la salud y enfermedad"},
	        {"FARMACIA", "Botica de remedios modernos"},
	        {"DOCTOR", "Sacerdote de la ciencia médica"},
	        {"ENFERMERO", "Ángel de batas blancas"},
	        {"MEDICINA", "Arte de vencer a la enfermedad"},
	        {"PELICULA", "Sueño proyectado en pantalla"},
	        {"SERIE", "Novela visual por capítulos"},
	        {"ACTOR", "Mentiroso profesional creíble"},
	        {"ACTRIS", "Ilusionista de emociones ajenas"},
	        {"DIRECTOR", "Dios del mundo ficticio"},
	        {"GUION", "Mapa del camino ficticio"},
	        {"ESCENA", "Trozo de vida representada"},
	        {"PUBLICO", "Colección de miradas expectantes"},
	        {"TEATRO", "Templo de la representación"},
	        {"PINTURA", "Emoción atrapada en color"},
	        {"DIBUJO", "Línea que cobra significado"},
	        {"COLOR", "Luz descompuesta en emociones"},
	        {"PINCEL", "Varita mágica del pintor"},
	        {"LIENZO", "Campo de batalla del artista"},
	        {"GALERIA", "Museo en miniatura comercial"},
	        {"MUSEO", "Cementerio de cosas vivas"},
	        {"ARTE", "Lenguaje sin palabras universales"},
	        {"ARTISTA", "Traductor de lo invisible"},
	        {"OBRA", "Hijo inmaterial del creador"},
	        {"TIENDA", "Templo del consumo diario"},
	        {"MERCADO", "Caos organizado de ofertas"},
	        {"SUPER", "Laberinto de estanterías llenas"},
	        {"CAJA", "Última frontera antes de llevar"},
	        {"CLIENTE", "Rey momentáneo del comercio"},
	        {"VENDEDOR", "Puente entre producto y bolsillo"},
	        {"PRECIO", "Número que vale un objeto"},
	        {"OFERTA", "Tentación con descuento"},
	        {"COMPRA", "Cambio de dinero por objetos"},
	        {"VENTA", "Magia de convertir cosas en dinero"},
	        {"COMPUTADORA", "Cerebro artificial programable"},
	        {"IMPRESORA", "Fuente de palabras en papel"},
	        {"ESCANER", "Ojo digital que captura lo plano"},
	        {"TELEVISOR", "Espejo de mundos ajenos"},
	        {"CONSOLA", "Puerta a mundos interactivos"},
	        {"JOYSTICK", "Timón de aventuras virtuales"},
	        {"VOLANTE", "Mandos del vehículo terrestre"},
	        {"FRENO", "Poder para detener el movimiento"},
	        {"ACELERADOR", "Llave de la velocidad"},
	        {"MOTOR", "Corazón mecánico que late"},
	        {"CARROCERIA", "Piel metálica del vehículo"},
	        {"NEUMATICO", "Anillo de goma que rueda"},
	        {"GASOLINA", "Sangre fósil de los motores"},
	        {"DIESEL", "Combustible pesado y ruidoso"},
	        {"ELECTRICO", "Energía silenciosa y limpia"},
	        {"BATERIA", "Pila de energía almacenada"},
	        {"CARGADOR", "Fuente de vida artificial"},
	        {"ENCHUFE", "Boca de la pared que da energía"},
	        {"CORRIENTE", "Río invisible de electrones"},
	        {"VOLTAJE", "Fuerza de la electricidad"},
	        {"PROGRAMACION", "Arte de hablar con máquinas"},
	        {"ALGORITMO", "Receta infalible para máquinas"},
	        {"VARIABLE", "Caja con nombre que cambia"},
	        {"FUNCION", "Máquina matemática en código"},
	        {"CLASE", "Molde para crear objetos"},
	        {"OBJETO", "Cosa digital con propiedades"},
	        {"METODO", "Acción que sabe hacer un objeto"},
	        {"CODIGO", "Lenguaje secreto de las máquinas"},
	        {"COMPILAR", "Traducir a lengua de máquina"},
	        {"EJECUTAR", "Dar vida al código escrito"},
	        {"INTERNET", "Telaraña global de información"},
	        {"NAVEGADOR", "Ventana a la red mundial"},
	        {"PAGINA", "Isla de información en la red"},
	        {"ENLACE", "Puente entre páginas web"},
	        {"BUSCAR", "Pescar información en el océano digital"},
	        {"RESULTADO", "Respuesta del oráculo digital"},
	        {"DESCARGAR", "Bajar bits del cielo digital"},
	        {"SUBIR", "Elevar datos a la nube"},
	        {"ARCHIVO", "Cápsula digital de información"},
	        {"CARPETA", "Cajón virtual para archivos"},
	        {"DOCUMENTO", "Papel digital que no se arruga"},
	        {"PRESENTACION", "Show de diapositivas digitales"},
	        {"CALCULO", "Matemática automatizada"},
	        {"FORMULA", "Receta matemática mágica"},
	        {"CELDA", "Cuadrícula numérica en tabla"},
	        {"FILA", "Línea horizontal de datos"},
	        {"COLUMNA", "Línea vertical de información"},
	        {"TABLA", "Rejilla ordenada de datos"},
	        {"GRAFICO", "Dibujo que habla con números"},
	        {"DIAGRAMA", "Mapa visual de procesos"},
	        
	        // ============ NIVEL FÁCIL FASE 3 ============
	        {"UNIVERSIDAD", "Fábrica de títulos y conocimiento"},
	        {"FACULTAD", "Tribu académica especializada"},
	        {"CARRERA", "Camino marcado hacia un título"},
	        {"MATERIA", "Trozo del saber universal"},
	        {"PROFESOR", "Guía remunerado del aprendizaje"},
	        {"ESTUDIANTE", "Esponja que absorbe conocimiento"},
	        {"EXAMENES", "Ritual de evaluación escrita"},
	        {"APROBAR", "Superar el filtro académico"},
	        {"SUSPENDER", "Tropezar en el camino del saber"},
	        {"NOTAS", "Calificaciones numéricas del esfuerzo"},
	        {"BIBLIOTECA", "Cementerio de libros vivos"},
	        {"LIBROS", "Prisiones de papel con ideas"},
	        {"REVISTAS", "Periódicos con mejor vestimenta"},
	        {"PERIODICO", "Historia diaria desechable"},
	        {"LECTOR", "Viajero de páginas ajenas"},
	        {"ESCRITOR", "Dios de pequeños universos en papel"},
	        {"NOVELA", "Mentira larga y bien contada"},
	        {"POESIA", "Matemática del alma en palabras"},
	        {"CUENTO", "Verdad disfrazada de ficción breve"},
	        {"HISTORIA", "Eco del pasado que nos forma"},
	        {"DEPORTISTA", "Guerrero del estadio"},
	        {"ENTRENADOR", "General sin guerra real"},
	        {"COMPETIR", "Medirse contra otros"},
	        {"CAMPEON", "Rey temporal de una disciplina"},
	        {"RECORD", "Límite esperando ser roto"},
	        {"MEDALLA", "Círculo de metal que vale esfuerzo"},
	        {"TROFEO", "Estatuilla que prueba triunfo"},
	        {"ESTADIO", "Anfiteatro moderno para deportes"},
	        {"PISTA", "Camino marcado para correr"},
	        {"CAMPO", "Tierra de juego delimitada"},
	        {"VACACIONES", "Tiempo robado al trabajo"},
	        {"VIAJE", "Movimiento con propósito de retorno"},
	        {"HOTEL", "Casa prestada por dinero"},
	        {"PLAYA", "Frontera donde tierra besa mar"},
	        {"MONTAÑA", "Gigante de piedra dormido"},
	        {"BOSQUE", "Ciudad de árboles y silencio"},
	        {"DESIERTO", "Océano de arena sin agua"},
	        {"CIUDAD", "Colmena humana de cemento"},
	        {"PUEBLO", "Ciudad en miniatura con alma"},
	        {"ALDEA", "Pueblo más pequeño aún"},
	        {"RESTAURANTE", "Teatro donde la comida es estrella"},
	        {"COMENSAL", "Espectador que devora la obra"},
	        {"MENU", "Carta de deseos comestibles"},
	        {"PLATO", "Obra de arte efímera y sabrosa"},
	        {"BEBIDA", "Líquido que acompaña o sacia"},
	        {"POSTRE", "Dulce final de la comida"},
	        {"CUENTA", "Resumen monetario del placer"},
	        {"PROPINA", "Agradecimiento monetario voluntario"},
	        {"CAMARERO", "Sirviente profesional de mesas"},
	        {"COCINERO", "Alquimista de sabores"},
	        {"INGENIERIA", "Arte de hacer posible lo necesario"},
	        {"ARQUITECTURA", "Poesía espacial habitable"},
	        {"MEDICINA", "Ciencia de luchar contra la muerte"},
	        {"DERECHO", "Sistema de reglas de convivencia"},
	        {"ECONOMIA", "Matemática aplicada al dinero"},
	        {"PSICOLOGIA", "Cartografía de la mente humana"},
	        {"FILOSOFIA", "Arte de preguntar sin responder"},
	        {"HISTORIA", "Eco organizado del pasado"},
	        {"GEOGRAFIA", "Ciencia de los lugares"},
	        {"MATEMATICA", "Lenguaje universal de los números"},
	        {"QUIMICA", "Magia controlada de las moléculas"},
	        {"FISICA", "Reglas del universo escritas"},
	        {"BIOLOGIA", "Estudio de la vida que vive"},
	        {"GEOLOGIA", "Historia escrita en piedras"},
	        {"ASTRONOMIA", "Ojeada al vecindario cósmico"},
	        {"INFORMATICA", "Ciencia de lo artificialmente inteligente"},
	        {"ELECTRONICA", "Magia de los electrones controlados"},
	        {"MECANICA", "Arte de las cosas que se mueven"},
	        {"CIVIL", "Ingeniería de lo que se pisa"},
	        {"INDUSTRIAL", "Ciencia de fabricar en masa"},
	        {"LABORATORIO", "Templo del experimento controlado"},
	        {"EXPERIMENTO", "Pregunta hecha a la naturaleza"},
	        {"INVESTIGAR", "Cazar verdades escondidas"},
	        {"CIENTIFICO", "Cazador profesional de verdades"},
	        {"HIPOTESIS", "Suposición educada a verificar"},
	        {"TEORIA", "Verdad provisional aceptada"},
	        {"LEY", "Regla que la naturaleza obedece"},
	        {"PRINCIPIO", "Fundamento sobre el que se construye"},
	        {"FORMULA", "Conjuro matemático que funciona"},
	        {"ECUACION", "Igualdad con incógnita por resolver"},
	        {"GENERACION", "Grupo nacido en misma época"},
	        {"EVOLUCION", "Cambio lento hacia adaptación"},
	        {"DESARROLLO", "Crecimiento hacia complejidad"},
	        {"PROGRESO", "Avance hacia algo mejor"},
	        {"AVANCE", "Movimiento hacia delante"},
	        {"INNOVACION", "Novedad que cambia lo establecido"},
	        {"TECNOLOGIA", "Aplicación práctica del conocimiento"},
	        {"CIENCIA", "Método organizado de saber"},
	        {"DESCUBRIMIENTO", "Encontrar lo que siempre estuvo"},
	        {"INVENTO", "Creación de lo que no existía"},
	        {"COMUNICACION", "Puente entre mentes"},
	        {"INFORMACION", "Datos con significado"},
	        {"MENSAJE", "Paquete de información enviado"},
	        {"NOTICIA", "Información reciente importante"},
	        {"REPORTE", "Informe organizado de datos"},
	        {"ANUNCIO", "Grito comercial por atención"},
	        {"PUBLICIDAD", "Arte de vender sueños"},
	        {"MERCADEO", "Ciencia de conectar oferta y demanda"},
	        {"VENTAS", "Arte de convertir deseos en compras"},
	        {"CLIENTELA", "Conjunto de compradores habituales"},
	        
	        // ============ NIVEL MEDIO FASE 1 ============
	        {"SOFTWARE", "Alma intangible de la máquina"},
	        {"HARDWARE", "Cuerpo físico de lo digital"},
	        {"SISTEMA", "Conjunto de partes que funcionan juntas"},
	        {"PROGRAMA", "Conjunto de instrucciones ordenadas"},
	        {"INTERFAZ", "Frontera entre humano y máquina"},
	        {"PLATAFORMA", "Base sobre la que se construye"},
	        {"SERVIDOR", "Esclavo digital siempre disponible"},
	        {"CLIENTE", "Solicitante de servicios digitales"},
	        {"RED", "Telaraña de conexiones invisibles"},
	        {"CONEXION", "Vínculo entre dos puntos"},
	        {"DATOS", "Materia prima de la información"},
	        {"ARCHIVO", "Contenedor digital de datos"},
	        {"CARPETA", "Organizador virtual de archivos"},
	        {"DISCO", "Plato giratorio que guarda bits"},
	        {"MEMORIA", "Tablero mental de la computadora"},
	        {"PROCESO", "Tarea en ejecución"},
	        {"HILO", "Hilván de ejecución paralela"},
	        {"PUERTO", "Puerta de entrada/salida digital"},
	        {"PROTOCOLO", "Etiqueta para máquinas que hablan"},
	        {"PAQUETE", "Carta digital con dirección"},
	        {"ENCRIPTAR", "Disfrazar información con clave"},
	        {"DECODIFICAR", "Quitar el disfraz a lo encriptado"},
	        {"COMPRIMIR", "Hacer pequeño lo grande"},
	        {"DESCOMPRIMIR", "Recuperar tamaño original"},
	        {"FORMATEAR", "Borrar y preparar para nuevo uso"},
	        {"INSTALAR", "Colocar programa en su hogar digital"},
	        {"DESINSTALAR", "Echar programa de su casa digital"},
	        {"ACTUALIZAR", "Dar nueva versión a lo existente"},
	        {"PARCHE", "Remiendo digital para fallos"},
	        {"VERSION", "Edición numerada de software"},
	        {"LENGUAJE", "Idioma para hablar con máquinas"},
	        {"SINTAXIS", "Gramática de los lenguajes artificiales"},
	        {"SEMANTICA", "Significado detrás del código"},
	        {"VARIABLE", "Caja con nombre que guarda valores"},
	        {"CONSTANTE", "Valor que no sabe cambiar"},
	        {"OPERADOR", "Símbolo que realiza acción"},
	        {"EXPRESION", "Frase matemática en código"},
	        {"SENTENCIA", "Orden completa para la máquina"},
	        {"BUCLE", "Camino circular en programación"},
	        {"CONDICION", "Pregunta que decide caminos"},
	        {"FUNCION", "Máquina pequeña dentro del código"},
	        {"PROCEDIMIENTO", "Serie de pasos con nombre"},
	        {"PARAMETRO", "Información que entra a función"},
	        {"ARGUMENTO", "Dato que acompaña a la llamada"},
	        {"RETORNO", "Respuesta que da una función"},
	        {"VALOR", "Dato concreto y específico"},
	        {"TIPO", "Especie a la que pertenece un dato"},
	        {"CLASE", "Molde para crear objetos digitales"},
	        {"OBJETO", "Instancia concreta de una clase"},
	        {"INSTANCIA", "Ejemplar único de un molde"},
	        {"MATERIA", "Sustancia de lo físico"},
	        {"ENERGIA", "Capacidad de hacer o cambiar"},
	        {"PARTICULA", "Trozo mínimo de materia"},
	        {"ATOMO", "Letra del alfabeto material"},
	        {"MOLECULA", "Palabra formada por átomos"},
	        {"ELEMENTO", "Sustancia pura de un solo tipo"},
	        {"COMPUESTO", "Unión química de elementos"},
	        {"MEZCLA", "Convivencia sin unión química"},
	        {"SOLUCION", "Mezcla homogénea de sustancias"},
	        {"REACCION", "Transformación química"},
	        {"GRAVEDAD", "Fuerza invisible que atrae"},
	        {"FUERZA", "Empuje o atracción física"},
	        {"MOVIMIENTO", "Cambio de posición en el tiempo"},
	        {"VELOCIDAD", "Rapidez con dirección"},
	        {"ACELERACION", "Cambio de la velocidad"},
	        {"MASA", "Cantidad de materia"},
	        {"PESO", "Fuerza que la gravedad ejerce"},
	        {"VOLUMEN", "Espacio que ocupa algo"},
	        {"DENSIDAD", "Masa por unidad de volumen"},
	        {"PRESION", "Fuerza repartida en área"},
	        {"TEMPERATURA", "Medida del calor interno"},
	        {"CALOR", "Energía que pasa de caliente a frío"},
	        {"FRIO", "Ausencia relativa de calor"},
	        {"TERMOMETRO", "Traductor de temperatura a números"},
	        {"BAROMETRO", "Medidor de peso del aire"},
	        {"MICROSCOPIO", "Ojo que ve lo invisible"},
	        {"TELESCOPIO", "Ojo que acerca lo lejano"},
	        {"ESPECTRO", "Arcoíris descompuesto científicamente"},
	        {"ONDAS", "Oscilaciones que transportan energía"},
	        {"SONIDO", "Onda que el oído interpreta"},
	        {"LUZ", "Onda que los ojos ven"},
	        {"COLOR", "Luz de frecuencia específica"},
	        {"REFLEXION", "Rebote de la luz o sonido"},
	        {"REFRACCION", "Doblaje de la luz al cambiar medio"},
	        {"DIFRACCION", "Esparcimiento de ondas"},
	        {"INTERFERENCIA", "Encuentro de ondas que se suman o restan"},
	        {"POLARIZACION", "Filtrar ondas en una dirección"},
	        {"LENTE", "Cristal que doma la luz"},
	        {"ESPEJO", "Superficie que devuelve imágenes"},
	        {"PRISMA", "Cristal que descompone la luz"},
	        {"ELECTRON", "Partícula con carga negativa"},
	        {"PROTON", "Partícula con carga positiva"},
	        {"NEUTRON", "Partícula sin carga eléctrica"},
	        {"NUCLEO", "Centro denso del átomo"},
	        {"ORBITA", "Camino circular de electrones"},
	        {"NIVEL", "Piso energético de electrones"},
	        {"ESTADO", "Condición física de la materia"},
	        {"FASE", "Estado específico de agregación"},
	        {"GAS", "Estado volátil y expansivo"},
	        {"LIQUIDO", "Estado fluido que toma forma del recipiente"},
	        
	        // ============ NIVEL MEDIO FASE 2 ============
	        {"ALGORITMO", "Receta paso a paso perfecta"},
	        {"ESTRUCTURA", "Andamio que sostiene datos"},
	        {"SECUENCIA", "Orden específico de elementos"},
	        {"ITERACION", "Repetición controlada"},
	        {"RECURSION", "Llamarse a sí mismo"},
	        {"OPTIMIZAR", "Hacer más con menos recursos"},
	        {"EFICIENCIA", "Relación entre logro y esfuerzo"},
	        {"COMPLEJIDAD", "Medida de lo enredado"},
	        {"ANALISIS", "Descomposición para entender"},
	        {"DISENO", "Plan antes de construir"},
	        {"IMPLEMENTAR", "Convertir plan en realidad"},
	        {"PROBAR", "Verificar que funciona"},
	        {"DEPURAR", "Cazar y eliminar errores"},
	        {"ERROR", "Desvío del camino esperado"},
	        {"EXCEPCION", "Situación inesperada manejable"},
	        {"VALIDAR", "Confirmar que es correcto"},
	        {"VERIFICAR", "Comprobar la verdad"},
	        {"COMPROBAR", "Asegurar mediante prueba"},
	        {"ASEGURAR", "Garantizar resultado"},
	        {"GARANTIZAR", "Prometer funcionamiento"},
	        {"DOCUMENTAR", "Explicar por escrito"},
	        {"COMENTARIO", "Nota para programadores"},
	        {"EXPLICAR", "Hacer comprensible"},
	        {"DESCRIBIR", "Pintar con palabras"},
	        {"DEFINIR", "Establecer significado exacto"},
	        {"ESPECIFICAR", "Detallar con precisión"},
	        {"REQUERIR", "Necesitar como condición"},
	        {"NECESITAR", "Tener falta de algo"},
	        {"REQUISITO", "Condición obligatoria"},
	        {"CONDICION", "Circunstancia necesaria"},
	        {"ARREGLO", "Colección ordenada de datos"},
	        {"MATRIZ", "Tabla bidimensional de datos"},
	        {"VECTOR", "Flecha con magnitud y dirección"},
	        {"LISTA", "Colección ordenada flexible"},
	        {"PILA", "Montón donde el último entra primero sale"},
	        {"COLA", "Fila donde el primero entra primero sale"},
	        {"ARBOL", "Estructura con raíz y ramas"},
	        {"GRAFO", "Puntos conectados por líneas"},
	        {"BUSQUEDA", "Encontrar lo específico"},
	        {"ORDENAR", "Poner en secuencia lógica"},
	        {"CLASIFICAR", "Agrupar por características"},
	        {"FILTRAR", "Dejar pasar solo algunos"},
	        {"SELECCIONAR", "Elegir entre opciones"},
	        {"INSERTAR", "Poner dentro de colección"},
	        {"ELIMINAR", "Quitar de donde está"},
	        {"MODIFICAR", "Cambiar características"},
	        {"ACTUALIZAR", "Poner al día"},
	        {"CAMBIAR", "Hacer diferente"},
	        {"BASE", "Fundamento sobre el que se construye"},
	        {"TABLA", "Organización en filas y columnas"},
	        {"REGISTRO", "Fila completa de datos"},
	        {"CAMPO", "Columna específica de datos"},
	        {"FILA", "Conjunto horizontal de datos"},
	        {"COLUMNA", "Conjunto vertical de datos"},
	        {"CLAVE", "Llave para identificar o acceder"},
	        {"PRIMARIA", "Clave única principal"},
	        {"FORANEA", "Clave que apunta a otra tabla"},
	        {"INDICE", "Guía rápida para buscar"},
	        {"CONSULTA", "Pregunta a la base de datos"},
	        {"SELECCION", "Elegir datos específicos"},
	        {"PROYECCION", "Elegir columnas específicas"},
	        {"UNION", "Juntar resultados de consultas"},
	        {"INTERSECCION", "Datos comunes entre conjuntos"},
	        {"DIFERENCIA", "Lo que está en uno pero no en otro"},
	        {"PRODUCTO", "Combinación de todas las filas"},
	        {"JUNTAR", "Unir tablas por campos comunes"},
	        {"DONDE", "Condición para filtrar"},
	        {"AGRUPAR", "Reunir por características comunes"},
	        {"ORDENAR", "Organizar por criterio"},
	        {"TENER", "Condición para grupos"},
	        {"DISTINTO", "Valores diferentes"},
	        {"AGREGADO", "Función que resume datos"},
	        {"CONTAR", "Función que enumera"},
	        {"SUMA", "Función que adiciona"},
	        {"PROMEDIO", "Función que calcula media"},
	        {"MINIMO", "Función que encuentra el menor"},
	        {"MAXIMO", "Función que encuentra el mayor"},
	        {"TRANSACCION", "Operación atómica completa o nada"},
	        {"COMPROMETER", "Confirmar cambios permanentemente"},
	        {"REVERTIR", "Deshacer cambios no comprometidos"},
	        {"PUNTOGUARDADO", "Marcador para volver atrás"},
	        {"BLOQUEO", "Impedir acceso concurrente"},
	        {"CONCURRENCIA", "Varios haciendo algo a la vez"},
	        {"CONSISTENCIA", "Estado lógico y correcto"},
	        {"AISLAMIENTO", "Separación de transacciones"},
	        {"DURABILIDAD", "Persistencia de cambios"},
	        {"ACIDO", "Propiedades de transacción confiable"},
	        {"NORMALIZAR", "Organizar para evitar redundancia"},
	        {"FORMA", "Estado de normalización"},
	        {"NORMAL", "Organizado según reglas"},
	        {"DENORMALIZAR", "Desorganizar por rendimiento"},
	        {"REDUNDANCIA", "Repetición innecesaria"},
	        {"INTEGRIDAD", "Calidad de estar completo y correcto"},
	        {"SEGURIDAD", "Protección contra accesos no deseados"},
	        {"AUDITORIA", "Registro de actividades"},
	        {"RESPALDO", "Copia de seguridad"},
	        
	        // ============ NIVEL MEDIO FASE 3 ============
	        {"PROTOCOLO", "Reglas para comunicación"},
	        {"ETHERNET", "Lenguaje de cables de red"},
	        {"ENRUTADOR", "Guía de paquetes en red"},
	        {"CONMUTADOR", "Director de tráfico local"},
	        {"CONCENTRADOR", "Punto común de conexión"},
	        {"PUENTE", "Unificador de segmentos de red"},
	        {"PASARELA", "Puerta entre redes diferentes"},
	        {"CORTFUEGOS", "Guardián de la red"},
	        {"PROXY", "Intermediario anónimo"},
	        {"INTERMEDIARIO", "Tercero en comunicación"},
	        {"DNS", "Traductor de nombres a números"},
	        {"DHCP", "Asignador automático de direcciones"},
	        {"HTTP", "Protocolo para páginas web"},
	        {"HTTPS", "HTTP con capa de seguridad"},
	        {"FTP", "Protocolo para transferir archivos"},
	        {"SMTP", "Protocolo para enviar correos"},
	        {"POP", "Protocolo para recibir correos"},
	        {"IMAP", "Protocolo moderno para correo"},
	        {"SSH", "Conexión segura a distancia"},
	        {"TELNET", "Conexión insegura a distancia"},
	        {"LAN", "Red de área local"},
	        {"WAN", "Red de área amplia"},
	        {"MAN", "Red de área metropolitana"},
	        {"VPN", "Red privada virtual"},
	        {"VLAN", "LAN virtual segmentada"},
	        {"WIFI", "Red sin cables por ondas"},
	        {"BLUETOOTH", "Red personal de corto alcance"},
	        {"INFRARROJO", "Comunicación por luz invisible"},
	        {"RADIOFRECUENCIA", "Comunicación por ondas de radio"},
	        {"MICROONDA", "Onda de alta frecuencia"},
	        {"ANCHOBANDA", "Capacidad de transmisión"},
	        {"RENDIMIENTO", "Eficiencia en resultados"},
	        {"LATENCIA", "Tiempo de respuesta"},
	        {"VARIACION", "Cambio en latencia"},
	        {"PAQUETE", "Fragmento de datos enviado"},
	        {"DATAGRAMA", "Paquete independiente"},
	        {"SEGMENTO", "Trozo de datos"},
	        {"ENCABEZADO", "Sombrero informativo del paquete"},
	        {"CONTENIDO", "Carga útil dentro del envoltorio"},
	        {"SUMACOMPROBACION", "Firma numérica para verificar integridad"},
	        {"ENRUTAMIENTO", "Arte de encontrar el mejor camino"},
	        {"REENVIO", "Pasar adelante lo recibido"},
	        {"DIFUSION", "Hablar a todos sin mirar a nadie"},
	        {"MULTIDIFUSION", "Hablar a un grupo selecto"},
	        {"UNDIFUSION", "Conversación privada punto a punto"},
	        {"CUALQUIERDIFUSION", "Gritar hasta que alguien responda"},
	        {"BANDAANCHA", "Autopista digital de varios carriles"},
	        {"BANDA", "Espacio para transmitir información"},
	        {"ANCHA", "Amplio camino para datos veloces"},
	        {"ESTRECHA", "Sendero digital de paso lento"},
	        {"ARQUITECTURA", "Plan maestro invisible"},
	        {"PATRON", "Modelo repetible de solución"},
	        {"SINGLETON", "Único ejemplar permitido"},
	        {"FABRICA", "Taller que produce objetos"},
	        {"OBSERVADOR", "Vigilante silencioso de cambios"},
	        {"ESTRATEGIA", "Plan cambiante según situación"},
	        {"ADAPTADOR", "Traductor entre interfaces incompatibles"},
	        {"DECORADOR", "Añadidos graduales sin modificar núcleo"},
	        {"FACHADA", "Cara bonita que esconde complejidad"},
	        {"MICROSERVICIO", "Órgano independiente del sistema"},
	        {"MONOLITO", "Gigante de piedra digital"},
	        {"SOA", "Filosofía de servicios orquestados"},
	        {"ESB", "Autopista central de mensajes"},
	        {"API", "Puerta con reglas para entrar"},
	        {"REST", "Estilo arquitectónico sin estado"},
	        {"SOAP", "Sobrecarga de protocolos en XML"},
	        {"GRAPHQL", "Lenguaje para pedir datos a medida"},
	        {"GRPC", "Conversación rápida entre servicios"},
	        {"GANCHO", "Punto para colgar funcionalidad extra"},
	        {"CONTENEDOR", "Cápsula aislada con todo incluido"},
	        {"DOCKER", "Fabricante de contenedores estandarizados"},
	        {"KUBERNETES", "Director de orquesta de contenedores"},
	        {"ORQUESTAR", "Dirigir la danza de contenedores"},
	        {"ESCALAR", "Crecer o encoger según demanda"},
	        {"REPLICAR", "Crear copias idénticas para resistencia"},
	        {"BALANCEAR", "Repartir carga equitativamente"},
	        {"CARGA", "Peso que soporta un sistema"},
	        {"GRUPO", "Conjunto que actúa como uno"},
	        {"NODO", "Punto en la red con identidad"},
	        {"CONTINUO", "Sin interrupciones, siempre fluyendo"},
	        {"INTEGRACION", "Unir piezas en un todo coherente"},
	        {"DESPLIEGUE", "Llevar software a su hogar final"},
	        {"ENTREGA", "Momento de dar el software terminado"},
	        {"TUBERIA", "Serie de procesos en cadena"},
	        {"FLUJOTRABAJO", "Camino predefinido de tareas"},
	        {"AUTOMATIZAR", "Quitar el factor humano repetitivo"},
	        {"GUION", "Receta para la automatización"},
	        {"CONFIGURAR", "Ajustar parámetros a necesidades"},
	        {"DESPLEGAR", "Poner en funcionamiento"},
	        {"MONITOREAR", "Observar constantemente el pulso"},
	        {"REGISTRO", "Diario de eventos del sistema"},
	        {"METRICA", "Número que mide algo importante"},
	        {"ALERTA", "Grito de auxilio del sistema"},
	        {"TABLERO", "Panel de control con indicadores"},
	        {"GRAFANA", "Artista de visualización de métricas"},
	        {"PROMETHEUS", "Cazador de métricas del sistema"},
	        {"ELASTICO", "Que se estira y encoge según necesidad"},
	        {"KIBANA", "Ventana para ver registros"},
	        {"LOGSTASH", "Procesador de registros en cadena"},
	     // Continuación NIVEL DIFÍCIL FASE 1
	        {"RETROPROPAGACION", "Aprendizaje por retroceso de errores"},
	        {"CONVOLUCIONAL", "Red que mira por ventanas"},
	        {"RECURRENTE", "Que tiene memoria de lo pasado"},
	        {"GENERATIVO", "Que puede crear nuevo contenido"},
	        {"DISCRIMINATIVO", "Que distingue entre categorías"},
	        {"CLASIFICACION", "Asignar etiquetas a entradas"},
	        {"REGRESION", "Predecir valores continuos"},
	        {"AGRUPAMIENTO", "Encontrar grupos naturales"},
	        {"ASOCIACION", "Descubrir relaciones entre elementos"},
	        {"SECUENCIA", "Serie ordenada en el tiempo"},
	        {"SERIE", "Sucesión de datos temporales"},
	        {"OPTIMIZACION", "Buscar el mejor posible"},
	        {"GRADIENTE", "Dirección de máximo cambio"},
	        {"DESCENDENTE", "Bajada por la pendiente del error"},
	        {"ESTOCASTICO", "Con elemento de aleatoriedad"},
	        {"MINILOTE", "Pequeño grupo de ejemplos"},
	        {"EPOCA", "Paso completo por todos los datos"},
	        {"ITERACION", "Ciclo de aprendizaje"},
	        {"CONVERGENCIA", "Llegar a punto estable"},
	        {"DIVERGENCIA", "Alejarse sin control"},
	        {"SOBREAJUSTE", "Memorizar en lugar de aprender"},
	        {"REGULARIZACION", "Poner límites al aprendizaje"},
	        {"ABANDONO", "Apagar neuronas aleatoriamente"},
	        {"NORMALIZACION", "Poner todos en misma escala"},
	        {"INICIALIZACION", "Dar valores iniciales"},
	        {"HE", "Método para inicializar pesos"},
	        {"XAVIER", "Otra forma de comenzar"},
	        {"ACTIVACION", "Función que decide si se enciende"},
	        {"RELU", "Activar solo si es positivo"},
	        {"SIGMOIDE", "Función en forma de S"},
	        {"TANH", "Sigmoides que va de -1 a 1"},
	        {"ENTROPIA", "Medida de incertidumbre"},
	        {"CRUZADA", "Entropía para clasificación"},
	        {"PERDIDA", "Cuánto se equivocó el modelo"},
	        {"FUNCION", "Matemática que mide error"},
	        {"COSTO", "Precio de los errores"},
	        {"PRECISION", "Cuántos aciertos tuvo"},
	        {"RECUERDO", "Cuántos de los relevantes encontró"},
	        {"F1", "Armonía entre precisión y recuerdo"},
	        {"MATRIZ", "Tabla de confusiones"},
	        {"CONFUSION", "Matriz que muestra aciertos y errores"},
	        {"ESTADISTICA", "Ciencia de analizar datos"},
	        {"PROBABILIDAD", "Posibilidad de que algo ocurra"},
	        {"DISTRIBUCION", "Forma en que se reparten valores"},
	        {"NORMAL", "Distribución en forma de campana"},
	        {"UNIFORME", "Todos los valores igualmente probables"},
	        {"BINOMIAL", "Distribución de éxitos y fracasos"},
	        {"POISSON", "Distribución de eventos raros"},
	        {"EXPONENCIAL", "Decaimiento constante"},
	        {"GAUSSIANA", "Otro nombre para normal"},
	        {"LAPLACE", "Distribución con colas pesadas"},
	        {"MEDIA", "Punto central promedio"},
	        {"MEDIANA", "Valor que parte la muestra en dos"},
	        {"MODA", "Valor más frecuente"},
	        {"VARIANZA", "Cuánto se dispersan los datos"},
	        {"DESVIACION", "Raíz cuadrada de la varianza"},
	        {"ESTANDAR", "Desviación típica normalizada"},
	        {"COVARIANZA", "Cómo varían dos variables juntas"},
	        {"CORRELACION", "Relación lineal entre variables"},
	        {"LINEAL", "Relación en línea recta"},
	        {"MULTIPLE", "Varias variables explicativas"},
	        {"LOGISTICA", "Clasificación con probabilidades"},
	        {"POLINOMIAL", "Relación en forma de curva"},
	        {"INTERPOLACION", "Estimar valores dentro del rango"},
	        {"EXTRAPOLACION", "Estimar valores fuera del rango"},
	        {"INTERVALO", "Rango de valores posibles"},
	        {"CONFIANZA", "Certeza medida en porcentaje"},
	        {"SIGNIFICANCIA", "Importancia estadística comprobada"},
	        {"HIPOTESIS", "Suposición a poner a prueba"},
	        {"NULA", "Hipótesis que niega efecto"},
	        {"ALTERNATIVA", "Hipótesis que afirma algo"},
	        {"PVALOR", "Probabilidad de error al rechazar nula"},
	        {"ALFA", "Umbral para decidir significancia"},
	        {"BETA", "Probabilidad de no detectar efecto real"},
	        {"POTENCIA", "Capacidad de detectar efectos verdaderos"},
	        {"PRUEBA", "Examen estadístico a los datos"},
	        {"TEST", "Procedimiento para tomar decisión"},
	        {"CHICUADRADO", "Prueba para tablas de contingencia"},
	        {"ANOVA", "Análisis de varianza entre grupos"},
	        {"MANNWHITNEY", "Prueba no paramétrica para dos grupos"},
	        {"KRUSKALWALLIS", "ANOVA no paramétrico"},
	        {"WILCOXON", "Prueba para muestras relacionadas"},
	        {"FRIEDMAN", "ANOVA no paramétrico para muestras relacionadas"},
	        {"SHAPIROWILK", "Prueba de normalidad de datos"},
	        {"KOLMOGOROV", "Prueba basada en distribución empírica"},
	        {"SMIRNOV", "Comparación de dos distribuciones"},
	        {"ANDERSONDARLING", "Prueba de bondad de ajuste sensible"},
	        {"LILLIEFORS", "Prueba de normalidad con parámetros estimados"},
	        {"JARQUEBERA", "Prueba basada en asimetría y curtosis"},
	        {"DAGOSTINO", "Prueba de normalidad robusta"},

	        // NIVEL DIFÍCIL FASE 2 (medicina)
	        {"CARDIOLOGIA", "Arte de escuchar los latidos del corazón"},
	        {"NEUROLOGIA", "Cartografía del laberinto cerebral"},
	        {"ONCOLOGIA", "Guerra científica contra invasores celulares"},
	        {"PEDIATRIA", "Medicina en escala reducida"},
	        {"GERIATRIA", "Ciencia del otoño humano"},
	        {"TRAUMATOLOGIA", "Reparador de huesos y tejidos dañados"},
	        {"CIRUGIA", "Arte con bisturí y precisión milimétrica"},
	        {"ORTOPEDIA", "Alineador de estructuras óseas torcidas"},
	        {"ODONTOLOGIA", "Cuidado de la entrada del cuerpo"},
	        {"ESTOMATOLOGIA", "Especialista de la boca y alrededores"},
	        {"OFTALMOLOGIA", "Médico de las ventanas del alma"},
	        {"DERMATOLOGIA", "Cartógrafo de la piel humana"},
	        {"GASTROENTEROLOGIA", "Especialista del tubo digestivo"},
	        {"NEFROLOGIA", "Cuidador de los filtros renales"},
	        {"UROLOGIA", "Especialista del sistema excretor"},
	        {"GINECOLOGIA", "Medicina específica femenina"},
	        {"OBSTETRICIA", "Arte de asistir nuevos comienzos"},
	        {"ENDOCRINOLOGIA", "Estudio de mensajeros químicos internos"},
	        {"HEMATOLOGIA", "Ciencia de la sangre y sus componentes"},
	        {"INMUNOLOGIA", "Estudio del sistema de defensa corporal"},
	        {"ANESTESIOLOGIA", "Arte del sueño médico controlado"},
	        {"RADIOLOGIA", "Ver a través de lo opaco"},
	        {"PATOLOGIA", "Estudio de las enfermedades"},
	        {"MICROBIOLOGIA", "Ciencia de lo invisible a simple vista"},
	        {"PARASITOLOGIA", "Estudio de los inquilinos no deseados"},
	        {"VIROLOGIA", "Ciencia de los límites de la vida"},
	        {"BACTERIOLOGIA", "Estudio de los unicelulares omnipresentes"},
	        {"MICOLOGIA", "Ciencia del reino fungi"},
	        {"PROTOZOOLOGIA", "Estudio de los animales unicelulares"},
	        {"HELMINTOLOGIA", "Ciencia de los gusanos parásitos"},
	        {"FARMACOLOGIA", "Ciencia de las sustancias que modifican"},
	        {"TOXICOLOGIA", "Estudio de los venenos y antídotos"},
	        {"BIOQUIMICA", "Química de los procesos vitales"},
	        {"FISIOLOGIA", "Ciencia del funcionamiento normal"},
	        {"ANATOMIA", "Cartografía del cuerpo humano"},
	        {"HISTOLOGIA", "Estudio de los tejidos microscópicos"},
	        {"EMBRIOLOGIA", "Ciencia del desarrollo temprano"},
	        {"GENETICA", "Estudio del código de la herencia"},
	        {"MOLECULAR", "Nivel de átomos y moléculas"},
	        {"CELULAR", "Nivel de las unidades básicas de vida"},
	        {"EPIDEMIOLOGIA", "Estudio de patrones de enfermedad"},
	        {"SALUD", "Estado de completo bienestar"},
	        {"PUBLICA", "Salud de las poblaciones"},
	        {"PREVENCION", "Evitar antes que curar"},
	        {"PROMOCION", "Fomentar hábitos saludables"},
	        {"REHABILITACION", "Recuperación de capacidades perdidas"},
	        {"FISIOTERAPIA", "Curación a través del movimiento"},
	        {"TERAPIA", "Tratamiento para curar o aliviar"},
	        {"OCUPACIONAL", "Terapia a través de actividades"},
	        {"LOGOPEDIA", "Corrección de trastornos del habla"},
	        {"CONSTITUCIONAL", "Derecho de la ley fundamental"},
	        {"ADMINISTRATIVO", "Derecho de la administración pública"},
	        {"PENAL", "Derecho de los delitos y penas"},
	        {"CIVIL", "Derecho de las relaciones privadas"},
	        {"MERCANTIL", "Derecho de los negocios"},
	        {"LABORAL", "Derecho del trabajo"},
	        {"FISCAL", "Derecho de los impuestos"},
	        {"TRIBUTARIO", "Derecho de las contribuciones"},
	        {"INTERNACIONAL", "Derecho entre naciones"},
	        {"PUBLICO", "Derecho que involucra al estado"},
	        {"PRIVADO", "Derecho entre particulares"},
	        {"PROCESAL", "Derecho del procedimiento judicial"},
	        {"CONTRACTUAL", "Derecho de los acuerdos"},
	        {"EXTRACONTRACTUAL", "Responsabilidad sin contrato"},
	        {"OBLIGACIONES", "Vínculos jurídicos de dar, hacer o no hacer"},
	        {"CONTRATOS", "Acuerdos con fuerza legal"},
	        {"SOCIEDADES", "Asociaciones con personalidad jurídica"},
	        {"ASOCIACIONES", "Uniones de personas con fin común"},
	        {"FUNDACIONES", "Patrimonio destinado a fin social"},
	        {"COOPERATIVAS", "Sociedades de ayuda mutua"},
	        {"PROPIEDAD", "Derecho de usar y disfrutar"},
	        {"INTELECTUAL", "Propiedad sobre creaciones de la mente"},
	        {"INDUSTRIAL", "Propiedad sobre signos distintivos"},
	        {"AUTOR", "Creador de obra intelectual"},
	        {"PATENTE", "Monopolio temporal sobre invento"},
	        {"MARCA", "Signo que distingue productos"},
	        {"REGISTRO", "Inscripción oficial para protección"},
	        {"DERECHOS", "Facultades reconocidas por ley"},
	        {"AUTORALES", "Derechos del creador sobre su obra"},
	        {"REPRODUCCION", "Multiplicación de copias"},
	        {"DISTRIBUCION", "Puesta a disposición del público"},
	        {"COMUNICACION", "Hacer accesible la obra"},
	        {"PUBLICA", "Acción ante audiencia"},
	        {"TRANSFORMACION", "Modificación de obra original"},
	        {"ADAPTACION", "Ajuste a diferentes medios"},
	        {"TRADUCCION", "Versión en otro idioma"},
	        {"CITA", "Mención breve de obra ajena"},
	        {"PARODIA", "Imitación burlesca permitida"},
	        {"CARICATURA", "Representación exagerada"},
	        {"PASTICHE", "Mezcla de estilos ajenos"},
	        {"ARBITRAJE", "Resolución por tercero neutral"},
	        {"MEDIACION", "Ayuda para llegar a acuerdo"},
	        {"CONCILIACION", "Encuentro para resolver diferencias"},
	        {"NEGOCIACION", "Diálogo para llegar a acuerdo"},
	        {"LITIGIO", "Conflicto llevado a tribunales"},
	        {"JUICIO", "Proceso judicial"},
	        {"SENTENCIA", "Decisión final del juez"},
	        {"APELACION", "Recurso a tribunal superior"},
	        {"CASACION", "Recurso por error de derecho"},
	        {"RECURSO", "Medio para impugnar decisión"},

	        // NIVEL DIFÍCIL FASE 3 (filosofía y tecnología)
	        {"EPISTEMOLOGIA", "Estudio del conocimiento mismo"},
	        {"ONTOLOGIA", "Pregunta sobre la existencia"},
	        {"METAFISICA", "Lo que está más allá de lo físico"},
	        {"ETICA", "Brújula moral del comportamiento"},
	        {"ESTETICA", "Filosofía de la belleza"},
	        {"LOGICA", "Matemática del pensamiento correcto"},
	        {"HERMENEUTICA", "Arte de interpretar significados"},
	        {"FENOMENOLOGIA", "Estudio de lo que aparece a la conciencia"},
	        {"EXISTENCIALISMO", "Filosofía de la libertad angustiosa"},
	        {"ESTRUCTURALISMO", "Ver patrones donde otros ven caos"},
	        {"POSESTRUCTURALISMO", "Crítica a los propios patrones"},
	        {"DECONSTRUCCION", "Desmontar supuestos ocultos"},
	        {"POSMODERNISMO", "Escepticismo hacia grandes relatos"},
	        {"CRITICA", "Análisis con juicio de valor"},
	        {"TEORIA", "Explicación sistemática de fenómenos"},
	        {"SOCIAL", "Relativo a la sociedad"},
	        {"SOCIOLOGIA", "Ciencia de la sociedad"},
	        {"ANTROPOLOGIA", "Estudio del ser humano integral"},
	        {"CULTURAL", "Relativo a los modos de vida"},
	        {"FISICA", "Psicología del cuerpo"},
	        {"PSICOLOGIA", "Ciencia de la mente y conducta"},
	        {"COGNITIVA", "Psicología de los procesos mentales"},
	        {"CONDUCTUAL", "Psicología del comportamiento observable"},
	        {"HUMANISTA", "Psicología del potencial humano"},
	        {"PSICOANALISIS", "Excavación del inconsciente"},
	        {"GESTALT", "Psicología del todo mayor a las partes"},
	        {"SISTEMICA", "Visión de interconexiones"},
	        {"TRANSPERSONAL", "Psicología más allá del ego"},
	        {"POSITIVA", "Psicología del bienestar"},
	        {"EVOLUTIVA", "Psicología del desarrollo"},
	        {"ECONOMIA", "Ciencia de la escasez y elección"},
	        {"POLITICA", "Ciencia del poder y gobierno"},
	        {"MICROECONOMIA", "Economía de individuos y empresas"},
	        {"MACROECONOMIA", "Economía de países y agregados"},
	        {"DESARROLLO", "Proceso de mejora económica"},
	        {"SUSTENTABLE", "Desarrollo que no compromete futuro"},
	        {"GLOBALIZACION", "Interconexión mundial creciente"},
	        {"NEOLIBERALISMO", "Ideología de mercado libre"},
	        {"KEYNESIANISMO", "Economía con intervención estatal"},
	        {"MARXISMO", "Análisis de lucha de clases"},
	        {"COMUNISMO", "Sociedad sin clases ni estado"},
	        {"SOCIALISMO", "Propiedad social de medios de producción"},
	        {"CAPITALISMO", "Sistema de propiedad privada y mercado"},
	        {"DEMOCRACIA", "Gobierno del pueblo"},
	        {"AUTOCRACIA", "Gobierno de uno solo"},
	        {"TOTALITARISMO", "Control total sobre sociedad"},
	        {"AUTORITARISMO", "Gobierno con poder concentrado"},
	        {"PLURALISMO", "Convivencia de diversidad"},
	        {"MULTICULTURALISMO", "Reconocimiento de culturas diversas"},
	        {"INTERCULTURALIDAD", "Diálogo entre culturas"},
	        {"NANOTECNOLOGIA", "Manipulación a escala atómica"},
	        {"BIOTECNOLOGIA", "Tecnología con seres vivos"},
	        {"AERONAUTICA", "Ciencia del vuelo atmosférico"},
	        {"ASTRONAUTICA", "Ciencia del vuelo espacial"},
	        {"ROBOTICA", "Ciencia de máquinas autónomas"},
	        {"MECATRONICA", "Fusión de mecánica y electrónica"},
	        {"AUTOMATIZACION", "Sustitución de trabajo humano"},
	        {"INSTRUMENTACION", "Medición y control de procesos"},
	        {"CONTROL", "Regulación de sistemas"},
	        {"PROCESOS", "Secuencia de operaciones"},
	        {"TELEMATICA", "Unión de telecomunicaciones e informática"},
	        {"TELECOMUNICACION", "Transmisión a distancia"},
	        {"SATELITAL", "Comunicación vía satélite"},
	        {"FIBRAOPTICA", "Transmisión por hilos de luz"},
	        {"OPTOELECTRONICA", "Unión de óptica y electrónica"},
	        {"FOTONICA", "Ciencia de los fotones"},
	        {"CUANTICA", "Física de lo muy pequeño"},
	        {"COMPUTACION", "Procesamiento de información"},
	        {"INFORMACION", "Datos con significado"},
	        {"CRIPTOGRAFIA", "Arte de los secretos escritos"},
	        {"HARDWARE", "Componentes físicos de computadora"},
	        {"DESCRIPTIVO", "Estadística que describe datos"},
	        {"VERILOG", "Lenguaje para describir hardware"},
	        {"VHDL", "Otro lenguaje de descripción hardware"},
	        {"FPGA", "Hardware reconfigurable"},
	        {"ASIC", "Circuito integrado específico"},
	        {"MICROPROCESADOR", "Cerebro de la computadora"},
	        {"MICROCONTROLADOR", "Computadora en un chip"},
	        {"DSP", "Procesador de señales digitales"},
	        {"GPU", "Procesador para gráficos"},
	        {"PARALELISMO", "Ejecución simultánea"},
	        {"CONCURRENCIA", "Avance simultáneo aparente"},
	        {"DISTRIBUIDO", "Sistema en múltiples lugares"},
	        {"ESCALABLE", "Que puede crecer sin problemas"},
	        {"RESILIENTE", "Que resiste fallos"},
	        {"TOLERANTE", "Que acepta errores sin caer"},
	        {"FALLOS", "Errores del sistema"},
	        {"RECUPERACION", "Volver a estado funcional"},
	        {"DESASTRE", "Evento catastrófico"},
	        {"CONTINGENCIA", "Plan para lo imprevisto"},
	        {"SUSTENTABILIDAD", "Capacidad de mantenerse en el tiempo"},
	        {"MEDIOAMBIENTE", "Entorno natural"},
	        {"ECOLOGICO", "Relativo al equilibrio natural"},
	        {"RENOVABLE", "Energía que no se agota"},
	        {"ENERGIA", "Capacidad de realizar trabajo"},
	        {"SOLAR", "Energía del sol"},
	        {"EOLICA", "Energía del viento"},
	        {"HIDRAULICA", "Energía del agua"},
	        {"GEOTERMICA", "Energía del calor terrestre"},
	        {"BIOMASA", "Energía de materia orgánica"},
	    };
			
			
			
		//DECALRAMOS VARIABLES
		int i;
		int j;
		boolean encontrado;
		//INICIALIZAMOS VARIABLES
		i = 0;
		j = 0;
		
		
		
		do {
			encontrado = false;
			j = 0;
			do {
			
			if (lineas[i][0].equals(enunciados[j][0])) {
				lineas[i][1] = enunciados[j][1];
				
				encontrado = true;
			} else {

				j++;
			}
			
			} while (j < enunciados.length && !encontrado);
			
			i++; 
			
		} while (i < lineas.length);
			
		
		
	}
}
